### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscriptions-gifting#233]
### Technical Checklist

- [x] [Check if WooCommerce is active](https://docs.woocommerce.com/document/create-a-plugin/#section-1)
- [x] [Main plugin file name matches plugin name](https://docs.woocommerce.com/document/create-a-plugin/#section-2)
- [x] [Text domain matches your plugin directory name](https://docs.woocommerce.com/document/create-a-plugin/#section-3)
- [x] [All plugin strings in English](https://docs.woocommerce.com/document/create-a-plugin/#section-4)
- [x] [Prevent Data Leaks by checking `ABSPATH` in all files](https://docs.woocommerce.com/document/create-a-plugin/#section-7)
- [x] [Contains Standard WordPress readme](https://docs.woocommerce.com/document/create-a-plugin/#section-8)
    - [x] [Link readme's Plugin URI to product/sale page on WooCommerce.com](https://docs.woocommerce.com/document/create-a-plugin/#section-11)
    - [x] [Declare required and supported WooCommerce versions in readme](https://docs.woocommerce.com/document/create-a-plugin/#section-10)
- [x] Add deploy script, similar to [Subscriptions](https://github.com/Prospress/woocommerce-subscriptions/blob/master/Gruntfile.js)
- [x] [Review UX standards](https://docs.woocommerce.com/document/user-experience-guidelines-ux/), especially onboarding notice/welcome

### Other

- [x] Create product page that complies with [Product Page Guidelines](https://docs.woocommerce.com/document/marketing-product-pages-writing/)
- [x] Create technical/user documentation that complies with [Documentation Guidelines](https://docs.woocommerce.com/document/writing-documentation/)
